# Generated by Django 5.0.6 on 2024-05-11 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('inGameId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ilvl', models.IntegerField()),
                ('gameSlot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('discordTag', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EPGPLogEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('DECAY', 'Decay'), ('DOCKEP', 'Dock EP'), ('DOCKGP', 'Dock GP'), ('LOOT', 'Loot'), ('PARTICIPATE', 'Participation'), ('STANDBY', 'Standby'), ('OTHER', 'Autre')], default='LOOT', max_length=20)),
                ('reason', models.CharField(default=None, max_length=200)),
                ('ep_delta', models.IntegerField(editable=False)),
                ('gp_delta', models.IntegerField(editable=False)),
                ('canceled', models.BooleanField(default=False)),
                ('loot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epgp.loot')),
                ('canceled_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player_canceled_by', to='epgp.player')),
                ('source_player_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='player_source_player_id', to='epgp.player')),
                ('target_player_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='player_target_player_id', to='epgp.player')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.IntegerField()),
                ('race', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=50)),
                ('spec', models.CharField(max_length=50)),
                ('playerId', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='epgp.player')),
            ],
        ),
    ]
