# Generated by Django 5.0.6 on 2024-05-11 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='spec',
        ),
        migrations.AddField(
            model_name='character',
            name='specAlt',
            field=models.CharField(choices=[('CAC', 'DPS Corps à Corps'), ('DISTANT', 'DPS Distant'), ('HEAL', 'Soigneur'), ('TANK', 'Tank')], default='DISTANT', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='specMain',
            field=models.CharField(choices=[('CAC', 'DPS Corps à Corps'), ('DISTANT', 'DPS Distant'), ('HEAL', 'Soigneur'), ('TANK', 'Tank')], default='DISTANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='classe',
            field=models.CharField(choices=[('DK', 'Chevalier de la mort'), ('DRUID', 'Druide'), ('HUNTER', 'Chasseur'), ('MAGE', 'Mage'), ('PALADIN', 'Paladin'), ('PRIEST', 'Pretre'), ('ROGUE', 'Voleur'), ('SHAMAN', 'Chaman'), ('WARLOCK', 'Demoniste'), ('WARRIOR', 'Guerrier')], default='MAGE', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='playerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epgp.player'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('UNDEAD', 'Mort Vivant'), ('TROLL', 'Troll'), ('TAUREN', 'Tauren'), ('ORC', 'Orc'), ('GOBELIN', 'Gobelin'), ('BLOODELF', 'Elf de Sang')], default='ORC', max_length=20),
        ),
        migrations.AlterField(
            model_name='epgplogentry',
            name='ep_delta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='epgplogentry',
            name='gp_delta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='epgplogentry',
            name='source_player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_source_player_id', to='epgp.player'),
        ),
        migrations.AlterField(
            model_name='epgplogentry',
            name='target_player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_target_player_id', to='epgp.player'),
        ),
    ]
