# Generated by Django 5.0.6 on 2024-06-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0002_alter_raid_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='isclosed',
            field=models.BooleanField(default=False, verbose_name='Terminé'),
        ),
    ]
