# Generated by Django 5.0.6 on 2024-05-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0002_remove_character_spec_character_specalt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='playerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='epgp.player'),
        ),
        migrations.AlterField(
            model_name='epgplogentry',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_canceled_by', to='epgp.player'),
        ),
        migrations.AlterField(
            model_name='epgplogentry',
            name='loot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loot', to='epgp.loot'),
        ),
    ]
