# Generated by Django 5.0.6 on 2024-05-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0003_alter_character_playerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ilvl',
            field=models.IntegerField(default=0, verbose_name='ilvl'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='classe',
            field=models.CharField(choices=[('DK', 'Chevalier de la mort'), ('DRUID', 'Druide'), ('HUNTER', 'Chasseur'), ('MAGE', 'Mage'), ('PALADIN', 'Paladin'), ('PRIEST', 'Pretre'), ('ROGUE', 'Voleur'), ('SHAMAN', 'Chaman'), ('WARLOCK', 'Demoniste'), ('WARRIOR', 'Guerrier')], default='MAGE', max_length=20, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Personnage'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('UNDEAD', 'Mort Vivant'), ('TROLL', 'Troll'), ('TAUREN', 'Tauren'), ('ORC', 'Orc'), ('GOBELIN', 'Gobelin'), ('BLOODELF', 'Elf de Sang')], default='ORC', max_length=20, verbose_name='Race'),
        ),
        migrations.AlterField(
            model_name='character',
            name='specAlt',
            field=models.CharField(choices=[('CAC', 'DPS Corps à Corps'), ('DISTANT', 'DPS Distant'), ('HEAL', 'Soigneur'), ('TANK', 'Tank')], default='DISTANT', max_length=20, verbose_name='Spécialisation secondaire'),
        ),
        migrations.AlterField(
            model_name='character',
            name='specMain',
            field=models.CharField(choices=[('CAC', 'DPS Corps à Corps'), ('DISTANT', 'DPS Distant'), ('HEAL', 'Soigneur'), ('TANK', 'Tank')], default='DISTANT', max_length=20, verbose_name='Spécialisation principale'),
        ),
        migrations.AlterField(
            model_name='epgplogentry',
            name='loot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loot', to='epgp.loot'),
        ),
        migrations.AlterField(
            model_name='player',
            name='discordTag',
            field=models.CharField(max_length=40, unique=True, verbose_name='Tag discord'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Joueur'),
        ),
    ]
