# Generated by Django 5.0.6 on 2024-06-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0003_raid_isclosed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raid',
            old_name='isclosed',
            new_name='isClosed',
        ),
    ]
