# Generated by Django 5.0.6 on 2024-05-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0004_character_ilvl_alter_character_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loot',
            name='gameSlot',
            field=models.IntegerField(verbose_name='Slot'),
        ),
        migrations.AlterField(
            model_name='loot',
            name='ilvl',
            field=models.IntegerField(verbose_name='Niveau item'),
        ),
        migrations.AlterField(
            model_name='loot',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
    ]
