# Generated by Django 5.0.6 on 2024-06-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0004_rename_isclosed_raid_isclosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isPU',
            field=models.BooleanField(default=False, verbose_name='Pick Up'),
        ),
    ]
