# Generated by Django 5.0.6 on 2024-11-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0005_player_ispu'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='loot',
            name='inGameId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ItemID'),
        ),
    ]
