# Generated by Django 5.0.6 on 2024-05-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0006_alter_epgplogentry_canceled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='participants',
            field=models.ManyToManyField(related_name='participant', to='epgp.character', verbose_name='Participants'),
        ),
    ]
