# Generated by Django 5.0.6 on 2024-05-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0007_alter_raid_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='commentaire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='raid',
            name='instance',
            field=models.CharField(choices=[('ICC', 'Icecrown Citadel'), ('BARADIN', 'Baradin Hold'), ('BASTION', 'Bastion of Twilight'), ('THRONE', 'Throne of the Four Winds'), ('FIRELAND', 'Firelands'), ('DRAGON', 'Dragon Soul')], default='BARADIN', max_length=20, verbose_name='Instance'),
        ),
        migrations.AlterField(
            model_name='raid',
            name='played_at',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
