# Generated by Django 5.0.6 on 2024-05-12 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0008_raid_commentaire_raid_instance_alter_raid_played_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='played_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 15, 54, 15, 837630), verbose_name='Date'),
        ),
    ]
