# Generated by Django 5.0.6 on 2024-05-12 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0009_alter_raid_played_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='played_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 17, 33, 53, 968914), verbose_name='Date'),
        ),
    ]
