# Generated by Django 5.0.6 on 2024-05-12 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0010_alter_raid_played_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='instance',
            field=models.CharField(choices=[('ICC', 'Icecrown Citadel'), ('BARADIN', 'Baradin Hold'), ('BASTION', 'Bastion of Twilight'), ('THRONE', 'Throne of the Four Winds'), ('FIRELAND', 'Firelands'), ('DRAGON', 'Dragon Soul'), ('AUTRE', 'Autre')], default='BARADIN', max_length=20, verbose_name='Instance'),
        ),
        migrations.AlterField(
            model_name='raid',
            name='played_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
