# Generated by Django 5.0.6 on 2024-05-18 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0012_player_isofficier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epgplogentry',
            name='source_player_id',
        ),
        migrations.AddField(
            model_name='epgplogentry',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='epgplogentry',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_canceled_by', to=settings.AUTH_USER_MODEL, verbose_name='Effacé par'),
        ),
        migrations.AlterField(
            model_name='epgplogentry',
            name='type',
            field=models.CharField(choices=[('NEWPLAYER', 'Nouveau Joueur'), ('DECAY', 'Decay'), ('DOCKEP', 'Pénalité EP'), ('DOCKGP', 'Pénalité GP'), ('LOOT', 'Loot'), ('PARTICIPATE', 'Participation'), ('STANDBY', 'Bench'), ('OTHER', 'Autre')], default='LOOT', max_length=20, verbose_name='Type'),
        ),
    ]
