# Generated by Django 5.0.6 on 2024-05-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0014_alter_epgplogentry_target_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='isOfficier',
            field=models.BooleanField(default=False, verbose_name='Officier'),
        ),
    ]
