# Generated by Django 5.0.6 on 2024-05-19 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epgp', '0016_alter_epgplogentry_canceled_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ilvl',
            field=models.IntegerField(verbose_name="Niveau d'item"),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom du personnage'),
        ),
        migrations.AlterField(
            model_name='character',
            name='playerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='epgp.player', verbose_name='Nom du Joueur'),
        ),
    ]
