on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    environment: prd
    
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: stop service
      continue-on-error: true
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "systemctl stop lbdb-django.service && exit"
    - name: clone repo
      continue-on-error: true
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && if [ ! -d directory ]; then git clone ${{ secrets.REPO_URL }} django fi && exit"
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/django && git restore . && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
    - name: replace config variables
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sh ${{ secrets.WORK_DIR }}/django/variabilise.sh ${{ secrets.DB_HOST }} ${{ secrets.DB_PORT }} ${{ secrets.DB_USER }} ${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} ${{ secrets.WORK_DIR }}/django/mysql.conf && exit"
    - name: init venv
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/django && python3.11 -m venv .venv && exit"
    - name: Replace settings file
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/django && rm ${{ secrets.WORK_DIR }}/django/djangoepgp/settings.py && mv ${{ secrets.WORK_DIR }}/django/djangoepgp/settings-prd.py ${{ secrets.WORK_DIR }}/django/djangoepgp/settings.py && exit"
    - name: install requierements
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/django && source .venv/bin/activate && python3.11 -m pip install -r requirements.txt && exit"
    - name: make migrations
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/django && source .venv/bin/activate && python3.11 manage.py makemigrations && exit"
    - name: migrate
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/django && source .venv/bin/activate && python3.11 manage.py migrate && exit"
    - name: collect static
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/django && source .venv/bin/activate && python3.11 manage.py collectstatic --noinput && exit"
    - name: install service
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sh ${{ secrets.WORK_DIR }}/django/install-service.sh && exit"
    - name: start service
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "systemctl --user daemon-reload && systemctl --user start lbdb-django.service && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
